export const Default = "Default";
export const Custom = "Custom";
export const userRoles = {
  superAdmin: "Super Admin",
};

export const UIActions = {
  ADD_ROLE: "Add Role",
  EDIT_ROLE: "Edit Role",
  LIST_ROLE: "List Role",
  VIEW_ROLE: "View Role",
  DELETE_ROLE: "Delete Role",
  CLONE_ROLE: "Clone Role",
  IMPORT_ROLE: "Import Role",
  EXPORT_ROLE: "Export Role",
  PRINT_ROLE: "Print Role",
  DOWNLOAD_ROLE: "Download Role",
  MANAGE_ROLE: "Manage Role",
  ADD_AGENT: "Add Agent",
  EDIT_AGENT: "Edit Agent",
  LIST_AGENT: "List Agent",
  VIEW_AGENT: "View Agent",
  DELETE_AGENT: "Delete Agent",
  CLONE_AGENT: "Clone Agent",
  IMPORT_AGENT: "Import Agent",
  EXPORT_AGENT: "Export Agent",
  PRINT_AGENT: "Print Agent",
  DOWNLOAD_AGENT: "Download Agent",
  MANAGE_AGENT: "Manage Agent",
  EDIT_USER: "Edit User",
  LIST_USER: "List User",
  VIEW_USER: "View User",
  DELETE_USER: "Delete User",
  CLONE_USER: "Clone User",
  IMPORT_USER: "Import User",
  EXPORT_USER: "Export User",
  PRINT_USER: "Print User",
  DOWNLOAD_USER: "Download User",
  MANAGE_USER: "Manage User",
  ADD_PROPERTY: "Add Property",
  EDIT_PROPERTY: "Edit Property",
  LIST_PROPERTY: "List Property",
  VIEW_PROPERTY: "View Property",
  DELETE_PROPERTY: "Delete Property",
  CLONE_PROPERTY: "Clone Property",
  IMPORT_PROPERTY: "Import Property",
  EXPORT_PROPERTY: "Export Property",
  PRINT_PROPERTY: "Print Property",
  DOWNLOAD_PROPERTY: "Download Property",
  MANAGE_PROPERTY: "Manage Property",
  ADD_OFFER: "Add Offer",
  EDIT_OFFER: "Edit Offer",
  LIST_OFFER: "List Offer",
  VIEW_OFFER: "View Offer",
  DELETE_OFFER: "Delete Offer",
  CLONE_OFFER: "Clone Offer",
  IMPORT_OFFER: "Import Offer",
  EXPORT_OFFER: "Export Offer",
  PRINT_OFFER: "Print Offer",
  DOWNLOAD_OFFER: "Download Offer",
  MANAGE_OFFER: "Manage Offer",
  ADD_PAGE: "Add Page",
  EDIT_PAGE: "Edit Page",
  LIST_PAGE: "List Page",
  VIEW_PAGE: "View Page",
  DELETE_PAGE: "Delete Page",
  CLONE_PAGE: "Clone Page",
  IMPORT_PAGE: "Import Page",
  EXPORT_PAGE: "Export Page",
  PRINT_PAGE: "Print Page",
  DOWNLOAD_PAGE: "Download Page",
  MANAGE_PAGE: "Manage Page",
  ADD_SETTING: "Add Setting",
  EDIT_SETTING: "Edit Setting",
  LIST_SETTING: "List Setting",
  VIEW_SETTING: "View Setting",
  DELETE_SETTING: "Delete Setting",
  CLONE_SETTING: "Clone Setting",
  IMPORT_SETTING: "Import Setting",
  EXPORT_SETTING: "Export Setting",
  PRINT_SETTING: "Print Setting",
  DOWNLOAD_SETTING: "Download Setting",
  MANAGE_SETTING: "Manage Setting",
  ADD_TICKET_PRICE_TYPE: "Add Ticket Price Type",
  EDIT_TICKET_PRICE_TYPE: "Edit Ticket Price Type",
  LIST_TICKET_PRICE_TYPE: "List Ticket Price Type",
  VIEW_TICKET_PRICE_TYPE: "View Ticket Price Type",
  DELETE_TICKET_PRICE_TYPE: "Delete Ticket Price Type",
  CLONE_TICKET_PRICE_TYPE: "Clone Ticket Price Type",
  IMPORT_TICKET_PRICE_TYPE: "Import Ticket Price Type",
  EXPORT_TICKET_PRICE_TYPE: "Export Ticket Price Type",
  PRINT_TICKET_PRICE_TYPE: "Print Ticket Price Type",
  DOWNLOAD_TICKET_PRICE_TYPE: "Download Ticket Price Type",
  MANAGE_TICKET_PRICE_TYPE: "Manage Ticket Price Type",
  ADD_TICKET_PRICE: "Add Ticket Price",
  EDIT_TICKET_PRICE: "Edit Ticket Price",
  LIST_TICKET_PRICE: "List Ticket Price",
  VIEW_TICKET_PRICE: "View Ticket Price",
  DELETE_TICKET_PRICE: "Delete Ticket Price",
  CLONE_TICKET_PRICE: "Clone Ticket Price",
  IMPORT_TICKET_PRICE: "Import Ticket Price",
  EXPORT_TICKET_PRICE: "Export Ticket Price",
  PRINT_TICKET_PRICE: "Print Ticket Price",
  DOWNLOAD_TICKET_PRICE: "Download Ticket Price",
  MANAGE_TICKET_PRICE: "Manage Ticket Price",
  ADD_WALLET: "Add Wallet",
  EDIT_WALLET: "Edit Wallet",
  LIST_WALLET: "List Wallet",
  VIEW_WALLET: "View Wallet",
  DELETE_WALLET: "Delete Wallet",
  CLONE_WALLET: "Clone Wallet",
  IMPORT_WALLET: "Import Wallet",
  EXPORT_WALLET: "Export Wallet",
  PRINT_WALLET: "Print Wallet",
  DOWNLOAD_WALLET: "Download Wallet",
  MANAGE_WALLET: "Manage Wallet",
};
export const MOBILE_NUMBER_REGEX = "^[6-9][0-9]{9}$";
export const PINCODE_REGEX = "^[1-9][0-9]{5}$";


export const StatusData = [
  { label: "Active", value: "Active" },
  { label: "Inactive", value: "Inactive" },
];

export const PaymentMode = [
  { label: "Cash", value: "CASH" },
  { label: "Online", value: "ONLINE" },
  { label: "Wallet", value: "WALLET" },
];

export const DecisionData = [
  { label: "Yes", value: "Yes" },
  { label: "No", value: "No" },
];
